// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed.sql

package db

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :one
UPDATE feeds SET  feed_name = $2 WHERE feed_id = $1
RETURNING feed_id, feed_name, url, description, created_at
`

type CompleteTaskParams struct {
	FeedID   int32  `json:"feed_id"`
	FeedName string `json:"feed_name"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, completeTask, arg.FeedID, arg.FeedName)
	var i Feed
	err := row.Scan(
		&i.FeedID,
		&i.FeedName,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (feed_name, url, description) VALUES ($1, $2, $3)
RETURNING feed_id, feed_name, url, description, created_at
`

type CreateFeedParams struct {
	FeedName    string         `json:"feed_name"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.FeedName, arg.Url, arg.Description)
	var i Feed
	err := row.Scan(
		&i.FeedID,
		&i.FeedName,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE feed_id = $1
`

func (q *Queries) DeleteFeed(ctx context.Context, feedID int32) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, feedID)
	return err
}

const getAllFeeds = `-- name: GetAllFeeds :many
SELECT feed_id, feed_name, url, description, created_at FROM feeds
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetAllFeedsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllFeeds(ctx context.Context, arg GetAllFeedsParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.FeedID,
			&i.FeedName,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds SET  feed_name = $2, url=$3, description=$4 WHERE feed_id = $1
RETURNING feed_id, feed_name, url, description, created_at
`

type UpdateFeedParams struct {
	FeedID      int32          `json:"feed_id"`
	FeedName    string         `json:"feed_name"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.FeedID,
		arg.FeedName,
		arg.Url,
		arg.Description,
	)
	var i Feed
	err := row.Scan(
		&i.FeedID,
		&i.FeedName,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
