// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Feed struct {
	FeedID      int32          `json:"feed_id"`
	FeedName    string         `json:"feed_name"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
