// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (Feed, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	DeleteFeed(ctx context.Context, feedID int32) error
	GetAllFeeds(ctx context.Context, arg GetAllFeedsParams) ([]Feed, error)
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
